### ISSUE TITLE
How to add local books ?

### ISSUE THREAD

**Issue by iamxvbaba** [kai-tw/NovelGlide-Flutter#2]

**Comment by kai-tw** [comment]
Hi @iamxvbaba. To add a local book, please follow this instruction.

1. Navigate to the bookshelf.
2. Press the button with the plus symbol at the bottom right corner.
4. Give the book a name and a thumbnail (optional).
5. Submit the information.
6. Click the book that was created, then you will go to its table of contents.
7. Tap the button with the plus symbol at the bottom right corner.
8. Provide the number of this chapter, chapter name, and the **TXT** file.
9. Now you may find the chapter in the table of contents.

**Some further information**
- Chapter Number is required, but the name is not.
- If you didn't provide a chapter name, the content at the first line would be the name.

**Comment by iamxvbaba** [comment]
Got it, thank you for your positive response.
I also hope that the function of importing an entire book can be added in the future.

**Comment by kai-tw** [comment]
Fantastic! I add that feature to the to-do list. Thank you very much.
